---
layout: docs
permalink: /docs/concept-systems-and-registries/
title: Intro to concept systems and registries
# This will have illustrations added.
---

== Concept systems

We think and understand.

Let’s call any unit of our understanding a *concept*.

To knowledge with others, we come up with verbal *definitions* of our concepts.

To make referring to a concept easier, we map it to a succint representation.
In ISO 704, it is called a “designation”.

A common type of designation is a word, but
phrases, abbreviations, math notation or other graphic symbols—all are used to refer to certain concepts.

As we share knowledge, it may turn out that:

* Someone else has independently thought of the same concept, and gave it a different term.
* The same term can mean another concept to someone else.
* Same designation can map to different concepts in different fields of knowledge.

This may be especially inconvenient in standards and other technical documentation,
where even subtle ambiguities in interpretation may cause trouble.

To make sure everyone is on the same page, we may want to establish a *concept system* (ISO 704).

A concept system would:

* Track how designations map to concepts in a given field of knowledge.
* Mark which designations are preferred.
* Track how concepts relate to each other.

Glossarist offers an approach to managing such a system.


== Registries

To allow collaborative improvement of a concept system,
we may want to have processes for changes to be proposed and reviewed in a transparent way,
and a view of a system that shows concept evolution over time.

ISO/TC 211 addresses this challenge with item registration procedures in ISO 19135.

Glossarist implements ISO 19135 registry model for managing concepts and concept systems.
