name: deploy-master

on:
  workflow_dispatch:
  schedule:
    - cron: '42 */12 * * *'
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ deploy_master ]

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2

      - uses: paneron/dataset-build-action/build@main
        with:
          scaffolding: paneron/glossary-site-scaffolding

      - uses: paneron/dataset-build-action/aws-deploy@main
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          s3-bucket: ${{ secrets.S3_BUCKET_NAME }}
          cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
